### ISSUE TITLE
error

### ISSUE THREAD

**Issue by malik-taj76** [FahadYousafMahar/Easypay-WHMCS-Gateway#11]
when payment proceed this error occured kindly help where is the issue thanks
Error occured

Error occurred on  at easypay.easypaisa.com.pk.
Request Page: /easypay/Index.jsf
Error occurred while proces
sing request. Please try again later!
![easy](https://user-images.githubusercontent.com/63449121/112641583-52165080-8e64-11eb-832e-88903faa0711.png)

**Comment by FahadYousafMahar** [comment]
That's an error on EasyPaisa's end. It is not due to the the gateway module

**Comment by malik-taj76** [comment]
![image002](https://user-images.githubusercontent.com/63449121/112822559-89be0c00-90a1-11eb-91ff-be4150abe64e.png)
easypaisa agent reply against this error:
You are using an old checkout integration method. Kindly use the attached integration guide for the new checkout.

**Comment by FahadYousafMahar** [comment]
where's the integration guide provided to you ?
And you are getting that error on easypaisa sandbox (staging server).
Easypaisa often does not provide users with sandbox environment. So it is a
possibility that you have live credentials and are trying to use sandbox.

**Comment by malik-taj76** [comment]
[Uploading Easypay Checkout - Integration guide 6.1.pdf…]()

**Comment by malik-taj76** [comment]
i m not using sandbox

**Comment by FahadYousafMahar** [comment]
your screenshot "Store not in our records" shows easypaystg in url which is
staging server.

**Comment by abdulsamad544** [comment]
Brother, I think there are issues on Easypay system side. I recently integrated this plugin with new live credentials and this appears:

![image](https://user-images.githubusercontent.com/44818072/124313226-fefe1900-db89-11eb-8bb6-e07501e8478d.png)

I also added the file_put_contents('ep.log',print_r($_REQUEST, true)."\n\n",FILE_APPEND); inside EasyPay.php in callback folder but it also has an empty array printed. 
Array
(
)

Should we contact EasyPay for this?

Note: Sometimes instead of this error, an error appears: Redirection Checkout is not allowed. Contact your administrator.
