### ISSUE TITLE
Sandbox Issue not redirecting back to WHMCS

### ISSUE THREAD

**Issue by Shaz3e** [FahadYousafMahar/Easypay-WHMCS-Gateway#3]
Hi,

I am using this on sandbox account but I am having an error and when I check at EasyPaisa Portal Transaction Status changed from **INITIATED** to **DROPPED** approx after 20 minutes you think this occurs from EasyPaisa or the module itself and the url redirects to https://easypaystg.easypaisa.com.pk/easypay/faces/pg/site/AuthError.jsf

![Capture](https://user-images.githubusercontent.com/526602/59802287-24e95580-9302-11e9-8bf9-5951745bf69e.jpg)

IPN Handler: https://subdomain.maindomain.tld/modules/gateways/callback/EasyPay.php

**Comment by FahadYousafMahar** [comment]
It's generated by easypaisa portal but could also be because of module as
API requires autoredirect=0/1 according to the situation intended.

But in this particular case i suspect it to be happening because of ep portal. I've seen this happening when easypaisa made it mandatory for its request to be hashed. 
Hashing algorithm was new one and whenever a request was hashed in wrong way or the hashed request didn't match the original request an error was generated.

**Comment by Shaz3e** [comment]
I have escalated the issue at EasyPaisa support as well

**Comment by ahsniii1** [comment]
Assalam o alaikum bhai kia ham isy hosting k lea use kar sakty ha every thing is fine ha is k uper thk kam kar raha ha
